//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trading_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Exchange_Notice = new HashSet<Exchange_Notice>();
        }
    
        public int Client_ID { get; set; }
        public string Client_Name { get; set; }
        public string Client_Phone { get; set; }
        public string Client_Fax { get; set; }
        public string Client_Mobile { get; set; }
        public string Client_Email { get; set; }
        public string Client_WebSite { get; set; }
        public string Wh_Name { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exchange_Notice> Exchange_Notice { get; set; }
    }
}
