//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trading_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange_Notice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exchange_Notice()
        {
            this.Exchange_Notice_Item = new HashSet<Exchange_Notice_Item>();
        }
    
        public int EN_ID { get; set; }
        public string Wh_Name { get; set; }
        public System.DateTime EN_Date { get; set; }
        public int Client_ID { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exchange_Notice_Item> Exchange_Notice_Item { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
