//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trading_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Notice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply_Notice()
        {
            this.Supply_Notice_Item = new HashSet<Supply_Notice_Item>();
        }
    
        public int SN_ID { get; set; }
        public string Wh_Name { get; set; }
        public System.DateTime SN_Date { get; set; }
        public int Supplier_ID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply_Notice_Item> Supply_Notice_Item { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
