//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trading_Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer_Item
    {
        public string From_Wh_Name { get; set; }
        public string To_Wh_Name { get; set; }
        public int It_Code { get; set; }
        public int Amount { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<System.DateTime> Production_Date { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
